#!/bin/sh

export MAINPORGRAM=./../../build/bin/main_release.exe
export CONFINPUT=./conf
export LOGFILE=run-$1.log
export OMP_NUM_THREADS=$1
echo "OpenMP Threads Number: $OMP_NUM_THREADS" > $LOGFILE

time $MAINPORGRAM < $CONFINPUT >> $LOGFILE 
